name = "WasmTools"
uuid = "079659ab-0fe6-4960-8bee-b2567b69b199"
authors = ["arhik <arhik23@gmail.com>"]
version = "0.1.0"

[deps]
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticTools = "86c06d3c-3f03-46de-9781-57580aa96d0a"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Wasmer = "8b6544c4-d78b-4947-8efb-e940865fd006"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
