name = "WasmTools"
uuid = "079659ab-0fe6-4960-8bee-b2567b69b199"
authors = ["arhik <arhik23@gmail.com>"]
version = "0.1.0"

[deps]
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticTools = "86c06d3c-3f03-46de-9781-57580aa96d0a"
Wasmer = "8b6544c4-d78b-4947-8efb-e940865fd006"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
